import mongoose from 'mongoose';

const systemConfigSchema = new mongoose.Schema(
  {
    serviceEmail: { type: String, default: '' },
    smtpHost: { type: String, default: '' },
    smtpPort: { type: Number, default: 587 },
    encryptedPassword: { type: String, default: '' },
    tenantId: { type: String, default: '' },
    clientId: { type: String, default: '' },
    clientSecret: { type: String, default: '' },
    serviceUsername: { type: String, default: '' },

    telecastGraphAuthMode: { type: String, enum: ['application', 'delegated'], default: 'application' },
    telecastGraphAccountUsername: { type: String, default: '' },
    telecastGraphRefreshTokenEnc: { type: String, default: '' },
    telecastGraphTokenUpdatedAt: { type: Date, default: null },
    graphRefreshTokenEnc: { type: String, default: '' },
    mailAccessTokenEnc: { type: String, default: '' },
    mailRefreshTokenEnc: { type: String, default: '' },
    mailTokenExpiresAt: { type: Date, default: null },
    graphTokenUpdatedAt: { type: Date, default: null },
    notificationRowSignatures: { type: [String], default: [] },
    notificationLastCheckedAt: { type: Date, default: null },
    notificationLastNewRowsCount: { type: Number, default: 0 },
    notificationLastNewRows: { type: [String], default: [] },
    notificationLastNewRowsPreview: { type: [Object], default: [] },
    telecastLastEligibleRowsPreview: { type: [Object], default: [] },
    telecastAlertedKeys: { type: [String], default: [] },
    telecastAlertedRefNos: { type: [String], default: [] },
    telecastAlertSeededAt: { type: Date, default: null },
    telecastAlertSeededCount: { type: Number, default: 0 },
    telecastTemplateSubject: { type: String, default: 'New Tender Row: {{TENDER_NO}} - {{TENDER_NAME}}' },
    telecastTemplateBody: { type: String, default: 'A new tender row was detected.\nRef: {{TENDER_NO}}\nTender: {{TENDER_NAME}}\nClient: {{CLIENT}}\nGroup: {{GROUP}}\nType: {{TENDER_TYPE}}\nDate Received: {{DATE_TENDER_RECD}}\nValue: {{VALUE}}' },
    telecastTemplateStyle: { type: String, default: 'avenir_blue' },
    telecastSendDelayMinutes: { type: Number, default: 10 },
    approvalAlertEnabled: { type: Boolean, default: false },
    approvalAlertTemplateSubject: { type: String, default: 'Tender Approved by Tender Manager: {{TENDER_NO}} - {{TENDER_NAME}}' },
    approvalAlertTemplateBody: { type: String, default: 'A tender has been approved by the Tender Manager and is ready for SVP review.' },
    approvalAlertTemplateStyle: { type: String, default: 'avenir_blue' },
    deadlineAlertEnabled: { type: Boolean, default: false },
    deadlineAlertTemplateSubject: { type: String, default: 'Tender Deadline Tomorrow: {{TENDER_NO}} - {{TENDER_NAME}}' },
    deadlineAlertTemplateBody: { type: String, default: 'Reminder: {{TENDER_NAME}} is due on {{SUBMISSION_DATE}} for {{CLIENT}}.' },
    deadlineAlertTemplateStyle: { type: String, default: 'sunset_alert' },
    deadlineAlertClients: { type: [String], default: [] },
    issueReportTemplateStyle: { type: String, default: 'avenir_blue' },
    telecastGroupRecipients: {
      type: Object,
      default: {
        GES: [],
        GDS: [],
        GTS: [],
      },
    },
    telecastKeywordHelp: { type: [String], default: [] },
    telecastWeeklyStats: {
      type: [
        {
          weekKey: { type: String },
          startDate: { type: String },
          endDate: { type: String },
          newRowsCount: { type: Number, default: 0 },
          byGroup: { type: Object, default: {} },
          updatedAt: { type: Date, default: Date.now },
        },
      ],
      default: [],
    },
    pageRoleAccess: { type: Object, default: {} },
    pageRoleExcludeAccess: { type: Object, default: {} },
    pageEmailAccess: { type: Object, default: {} },
    actionRoleAccess: { type: Object, default: {} },
    actionEmailAccess: { type: Object, default: {} },
    postBidAllowedEmails: { type: [String], default: [] },
    exportTemplateSheetName: { type: String, default: 'Opportunities' },
    exportTemplateTitle: { type: String, default: 'Opportunity Export' },
    exportTemplateIntroText: { type: String, default: 'Generated from the Avenir dashboard export.' },
    exportTemplateShowLogo: { type: Boolean, default: true },
    exportTemplateLogoDataUrl: { type: String, default: '' },
    exportTemplateLogoRow: { type: Number, default: 1 },
    exportTemplateLogoColumn: { type: Number, default: 1 },
    exportTemplateLogoWidth: { type: Number, default: 150 },
    exportTemplateLogoHeight: { type: Number, default: 46 },
    exportTemplateTitleRow: { type: Number, default: 1 },
    exportTemplateTitleColumn: { type: Number, default: 3 },
    exportTemplateTitleRowSpan: { type: Number, default: 1 },
    exportTemplateTitleColumnSpan: { type: Number, default: 4 },
    exportTemplateTitleHorizontalAlign: { type: String, default: 'left' },
    exportTemplateTitleVerticalAlign: { type: String, default: 'middle' },
    exportTemplateIntroRow: { type: Number, default: 2 },
    exportTemplateIntroColumn: { type: Number, default: 3 },
    exportTemplateIntroRowSpan: { type: Number, default: 2 },
    exportTemplateIntroColumnSpan: { type: Number, default: 5 },
    exportTemplateIntroHorizontalAlign: { type: String, default: 'left' },
    exportTemplateIntroVerticalAlign: { type: String, default: 'top' },
    exportTemplateHeaderRow: { type: Number, default: 4 },
    exportTemplateHeaderColumn: { type: Number, default: 1 },
    exportTemplateHeaderHorizontalAlign: { type: String, default: 'left' },
    exportTemplateHeaderVerticalAlign: { type: String, default: 'middle' },
    exportTemplateHeaderBackgroundColor: { type: String, default: '#1D4ED8' },
    exportTemplateHeaderTextColor: { type: String, default: '#FFFFFF' },
    exportTemplateTitleColor: { type: String, default: '#0F172A' },
    exportTemplateIntroColor: { type: String, default: '#475569' },
    exportTemplateColumnWidths: { type: [Number], default: Array.from({ length: 12 }, () => 18) },
    exportTemplateRowHeights: { type: [Number], default: Array.from({ length: 20 }, () => 24) },
    lastUpdatedBy: { type: String, default: null },
    updatedBy: { type: String, default: null },
  },
  { timestamps: true }
);

export default mongoose.model('SystemConfig', systemConfigSchema);
